### ISSUE TITLE
References to quad need to be changed

### ISSUE THREAD

**Issue by jonlawlor** [gonum/integrate#19]
There are a variety of references to the quad package that need to be adjusted after the rename to integrate.

I would have opened a pull request but one place is in the github repo description: "quad implements a set of quadrature routines for the Go language" and that is not subject to modification via pulls.

I would suggest that it be renamed to:

"integrate implements numerical integration for the Go language"

**Comment by btracey** [comment]
I am in the middle of a PR fixing things, should I abandon?

**Comment by jonlawlor** [comment]
A PR is appropriate; I just wanted to talk about the description which can't be changed via pull.  We can have that discussion in the PR if you want!

**Comment by btracey** [comment]
Oh, I misunderstood.

**Comment by btracey** [comment]
Description modified. We can adjust again if we’d like.

**Comment by jonlawlor** [comment]
LGTM, closing.
